### ISSUE TITLE
Feature request: double click on dice slot to auto-pick one

### ISSUE THREAD

**Issue by jmickle66666666** [TerryCavanagh/diceydungeons.com#103]
This would provide an option to add dice to a slot with minimal mouse-travel time. The game would automatically pick a "best" dice from your available ones, according to some simple rules.

**Comment by TerryCavanagh** [comment]
Hey -

Thanks for the suggestion, but I don't think I'm going to do this one - I think there are certain types of automation that feel good and certain types that feel bad, and this one would feel bad, because it'd short circuit decision making.

That said, I've made some very cool UI changes for v0.5, so I suspect this might seem like less of an issue very soon. We'll see on friday, I suppose!

**Comment by jmickle66666666** [comment]
That makes sense!
