### ISSUE TITLE
Episodes selection screen wonky

### ISSUE THREAD

**Issue by calmcajun** [TerryCavanagh/diceydungeons.com#1169]
When you switch over from Warrior to Thief the Warrior's episodes are shown with no hover tooltip.

**Comment by shymu** [comment]
I'm seeing an even more severe version of this, where not only do the hover tooltips disappear but sometimes (like on Robot in the video linked below) the episodes box doesn't even appear until you go back to the Title screen and hit play again.

This is the Steam version on MacOS. I noticed there was an update this morning but the issue persists.

https://mega.nz/#!GCwjnIRb!sdceMyl35YUSATp7EEwxUL5isSV58aOz4IBzIC8ONoQ

**Comment by shymu** [comment]
Attaching a couple of screenshots since that might be easier for devs. On the first screenshot, I hit "Play" and then the right arrow twice. No box for episodes for Robot.

On the second screenshot, I pressed "Title" in top left, and then the "Play" button again and the episode box for Robot has re-appeared.

<img width="1392" alt="episode-1" src="https://user-images.githubusercontent.com/38837724/63225460-54033280-c19e-11e9-9ebe-c8e785503e84.png">
<img width="1392" alt="episode-2" src="https://user-images.githubusercontent.com/38837724/63225461-54033280-c19e-11e9-9bd0-5276e2feba3e.png">

**Comment by iestynne** [comment]
I had the missing hover text issue.
It seems like the hover text disappears when you switch character.
The text comes back if you exit to the title screen and hit play again.

**Comment by TerryCavanagh** [comment]
This one has been fixed now for a little while. Closing!
