### ISSUE TITLE
Pirate Hook? doesn't work correctly

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1185]
The Re-Equip Next? status is given to you AFTER Pirate Hook fires.

**Comment by TerryCavanagh** [comment]
Fixed! This required adding support for the actualdice array on some equipment scripts other than execute, which is a nice bonus.

Cards that grant a status effect that are immediately used are pretty hard to implement, so I just rewrote it without the status effect step - technically fine since the card doesn't actually specify Re-Equip Next? as the status effect. A bit messy, though!
