### ISSUE TITLE
Got normal weapon without counters in Inevitability of Rust

### ISSUE THREAD

**Issue by omor1** [TerryCavanagh/diceydungeons.com#1350]
I've somehow got a perfectly normal, counterless Plasma Bluster in the Inevitability of Rust episode. It's not reusable. I _think_ that it had been a "regular" Plasma Blaster (for the scenario; that is, with counters, etc.) that I had used up in the prior fight (hence the Plasma Gun). I have no idea how to go about reproducing this.

In the screenshot, it just got weakened by Loud Bird; I've circled it in blue. Found in v1.3.

![Plasma Blaster](https://user-images.githubusercontent.com/4326436/63990261-02657c80-caa9-11e9-86dd-1e8f55529ba3.png)

**Comment by omor1** [comment]
Using the Grindstone+ seems to have "fixed" the bug; I got the Plasma Blaster with a counter of 1.

**Comment by omor1** [comment]
My guess is that equipment without counters simply have a counter value of 0; the UI code then doesn't draw (a) counter box(es). Somehow the equipment wasn't destroyed when ticking down from 1 to 0, leading to this bug in the following fight (until I used the Grindstone).

**Comment by XenonZed** [comment]
Looks like this happens because Grindstone's script doesn't check whether or not an equipment actually has any uses remaining. Could probably be fixed by changing
`for(eq in self.equipment){ if(eq.name != ~Grindstone~ ){ eq.totalusesremaining++; eq.animate(~flash~); } }`
to
`for(eq in self.equipment){ if(eq.name != ~Grindstone~ && eq.totalusesremaining > 0 ){ eq.totalusesremaining++; eq.animate(~flash~); } }`

**Comment by TerryCavanagh** [comment]
Fixed in v2.2!
