### ISSUE TITLE
Alchemist AI can lockup if bear-transform triggered early

### ISSUE THREAD

**Issue by hunky-dory** [TerryCavanagh/diceydungeons.com#1406]
![Screenshot 2019-09-05 at 17 59 05](https://user-images.githubusercontent.com/48322734/64362696-e14fdf00-d006-11e9-9b0e-b997b3aa2f1f.png)

(Pirate Modifier may be involved somehow?)
1. Apply multiple shocks to Alchemist, such that she chooses to trigger bear transform while still having the three preceding cards
2. On the remainder of her bear turn, Alchemist places one dice to the left of Bear Maul, where it disappears as if into an invisible counter.
3. She doesn't do anything with the other dice at all

**Comment by JuniorUdale** [comment]
This is an issue with shocking Alchemist - a few other people have reported it:

https://steamcommunity.com/app/861540/discussions/0/1636418037463912750/
https://steamcommunity.com/app/861540/discussions/0/1636418037462354242/
https://steamcommunity.com/app/861540/discussions/0/1636418037459257482/

The steps to reproduce it **seem** to involve shocking Alchemist, most probably shocking her so that she prematurely activates Bear Potion.

**Comment by TerryCavanagh** [comment]
Fixed for v1.7!
