### ISSUE TITLE
You can add custom bosses, but trying to give them First Words that always play freezes the game when their dialogue should appear

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1513]
I've tried both _appending to and replacing specialenemyencounters.csv (with matching enemy name, level that goes up by 1 for each unique dialogue, and properly formatted dialogue), and no luck. Ignoring specialenemyencounters.csv and just inputting something directly into the First Words column of fighters.csv doesn't work either. Console outputs nothing when this occurs.

**Comment by TerryCavanagh** [comment]
I think this might just be due to how boss dialogue is implemented right now, which is pretty confusing tbh. You can see how it's supposed to be done in the Halloween Special mod (there's a special variable to specify the range of boss dialogue(. I'll clean this up a bit for the next version of the modding API.
