### ISSUE TITLE
As Inventor, if you have more than 1 gadget, your second gadget becomes the same as the first one

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1516]
For example, Inventor's Episode 2 has Heat Ray and Jetpack as starting gadgets, but she gets two Heat Rays instead.

**Comment by TerryCavanagh** [comment]
This was surprisingly tricky to track down! Ended up being caused by an indexing bug in the `Rules.inventor_setgadgets` function. Should be fixed in v1.7!

(I marked this bug as a high priority because I thought it meant that Double Rubble was completely broken, but turns out it only caused a problem for the initial gadgets, which was less serious. Phew!)
