### ISSUE TITLE
Console complains about an error whenever someone takes damage from poison

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1558]
![image](https://user-images.githubusercontent.com/11216597/68733166-d172ef00-05a3-11ea-8899-ed03b2d9d205.png)

**Comment by ncrecc** [comment]
The game doesn't crash or lag or anything, it just produces these errors

**Comment by TerryCavanagh** [comment]
Ah hah! Figured this one out. This was caused by the new "blockall" status effect implemented for the Halloween special - there was a check on self-inflicted damage to see if you had the blockall status effect if the enemy had thorns. However, with poison damage, there's no "actor" inflicting the attack, just a target - so the function was getting a null reference error when checking if the actor had thorns.

Obviously, poison damage shouldn't be checking to see if the opponent has thorns before calculating damage, so it was good to catch this - this error was actually concealing a more serious bug!
