### ISSUE TITLE
Vanish doesn't work on enemies

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1564]
This has been known for a while but never had an issue made for it. This is why Wisp is banned from most Thief and Inventor episodes

**Comment by chandl34** [comment]
It can show up in the Jester levels.

**Comment by TerryCavanagh** [comment]
Uff! Today's random bug. Ok, I guess it would be nice if this one worked properly!

**Comment by TerryCavanagh** [comment]
Fixed! https://streamable.com/is13fm

I've also made some related changes:
 - the Wisp remix rule applies to both the player and the enemy now, seems like a fun change
 - in Robot episode 2, this vanish effect is applied as a status effect rather than a "rule change", and only applies to the player. (probably how I should have done this in the first place)

**Comment by TerryCavanagh** [comment]
(oh, and I'm adding Wisp to more episodes! No need to exclude them from episodes with Steal anymore!)
