### ISSUE TITLE
Keymaster rule doesn't work correctly with Witch

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1584]
It errors her spells, but you can still get new spells from the spellbook.
![image](https://user-images.githubusercontent.com/32357485/70926066-52e6f280-2024-11ea-960c-ce6ffd351aa4.png)

Perhaps this rule could become "after making 6 moves per turn, all your dice are locked"? Would be essentially the same thing, only being changed a little with Jester and snaps.

**Comment by TerryCavanagh** [comment]
Fixed!

Thought about this a little, and went with the solution of all new spells you summon are unavailable that turn. This seemed like the most correct solution, since the game doesn't count summoning spells itself as a "move", so you can still use spare dice to set up your board for the next turn.

It's not perfect, though, as the issue of not knowing what unavailable spells actually are becomes pretty annoying here. Still, I have another issue about tackling that one, so happy to close this for now.
