### ISSUE TITLE
Consider making more equipment Special

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1621]
Currently there are quite a few items that either do nothing, or bug out when generated through random means like Jester's Robot card, or the Yolanda/Val remixes. Consider marking these as Special, or changing them so that they can work for other characters.

- Mechanical Arm/Forcefield. These work for Robot, but for no-one else. The "rolled" terminology could confuse players, especially if they try putting a dice into e.g. Juggling Ball and being confused as to why the damage isn't increasing.

- Fuse. Consider removing this completely?

- Incoming!. It only works for Jester, and even then the description isn't correct - it *permanently* adds that juggling ball to your deck.

- Delete. Again, only works for Jester, and is only really helpful in one episode.

- Forge, Spare Cycles - aren't properly implemented yet!

- Call for Backup cards. Warrior, Thief, Robot, and their PU equivalents are all probably fine to keep. Inventor and Witch (and their PU variants) both reference a "deck", which is only available for Jester. Personally I'd err on the side of not causing confusion to the player, by making those two special (but keep the rest non-special since they work)

- Lunasa, Memorise. Both of these reference your spellbook, and presumably do nothing for the other 5 characters.

- Uptick. It breaks a lot of things if you get this; AFAIK it can permanently replace your skillcard. It really should be made Special to avoid buggy things happening on the player's side.

**Comment by ncrecc** [comment]
Uptick could maybe just be re-coded so it doesn't try to change your skillcard unless it *is* your skillcard, and use giveequipment otherwise

**Comment by ncrecc** [comment]
Harvest Scythe and Spring Equinox also reference the spellbook

**Comment by Matz-42** [comment]
Alright just leaving a comment in order to complete the list:

- Combat Roll: While it works fine(ish), it can be obtained as a normal equipment and doesn't properly weaken.
- Wail/Squawk: While they don't break anything, obtaining them is essentially useless for the player.
- Mystery Box: Mystery box is very broken when actually used (and not replaced through Mimic's ability), giving size 2 equipments when it's only size 1
- Wooden Stake/Wooden Stake?: Obviously really weird when it is obtained outside of a Drake fight, as it actually does damage, but is also not meant to be really used outside of a specific fight.
- Dark Shadow@versusladyluck: Shouldn't appear at all outside of the last episode, while it's not breaking anything, it looks just like Dark Shadow and may confuse the player as to why they aren't getting some of the strongest status effects out of it (seemingly bad rng when it's actually just impossible)

**Comment by TerryCavanagh** [comment]
Added all of these (and more!) to v1.9! Thanks for the suggestions!
