### ISSUE TITLE
Polish translation needs healing (part 1?)

### ISSUE THREAD

**Issue by Linkyop** [TerryCavanagh/diceydungeons.com#1632]
So i'm going to post some basic issues/not correct translations in Polish. (1.7.1)

1.

> Credits

to

> Autorzy

![1](https://user-images.githubusercontent.com/60701198/73881271-5185b980-4860-11ea-90f9-7bbf65daa075.png)
----
2.

> Language
(requires restart)

to

> Język
(wymaga restartu)

> Voices volume

to

> Głośność głosów

![2](https://user-images.githubusercontent.com/60701198/73881273-52b6e680-4860-11ea-9462-8688128c99a0.png)
----
3,

> Tytuł

to

> Menu główne

And also text out of borders.

![3](https://user-images.githubusercontent.com/60701198/73881274-52b6e680-4860-11ea-8d94-534290b67d73.png)
----
4.

Text out of borders.

![4](https://user-images.githubusercontent.com/60701198/73881278-534f7d00-4860-11ea-8b9e-e42809cd8e22.png)
----
5.

> Poziom

is completely incorrect for this. It should be replaced to

> Piętro

which means "Floor".

![5](https://user-images.githubusercontent.com/60701198/73881280-534f7d00-4860-11ea-9df8-fad05faa007c.png)
----
6.

> Parzysta

is out of borders.

![6](https://user-images.githubusercontent.com/60701198/73881282-53e81380-4860-11ea-970d-d2615199b73c.png)
----
7.

> Zadaj obrażenia <value>

sounds wrong, because it means "Do damage 5" (5 for example), which sounds weird. Punctuation mark " : " should be added:

> Zadaj obrażenia: <value>

And Fury description is completely wrong, because now it says "Repeat next equipment **two times**", which means item will be used three times, which is not true. This should be corrected to:

> Powtórz użycie następnego przedmiotu.

![7](https://user-images.githubusercontent.com/60701198/73881283-5480aa00-4860-11ea-937c-3b99afa89414.png)
----
8.

> dodatkowa kostka!

should be corrected to

> dodatkową kostkę!

![8](https://user-images.githubusercontent.com/60701198/73881286-5480aa00-4860-11ea-9afd-4ff7e0e607bf.png)
----
9.

Text out of borders.

![9](https://user-images.githubusercontent.com/60701198/73881291-55194080-4860-11ea-9536-e485424b309c.png)

**Comment by TerryCavanagh** [comment]
Hey! Took me a while to get to this one.

I went through this list and for all the ones that were due to formatting or bugs on my end, I fixed! This is most of it. (e.g character cards, episode descriptions, some strings which weren't getting picked up like "Credits").

![image](https://user-images.githubusercontent.com/2874150/87911939-fc5afe80-cab3-11ea-990d-20a2add497de.png)

![image](https://user-images.githubusercontent.com/2874150/87912098-47751180-cab4-11ea-8491-464ffe015c78.png)

![image](https://user-images.githubusercontent.com/2874150/87913047-fa923a80-cab5-11ea-937e-a375e4155d0f.png)

With adding ":" to equipment with descriptions like "Zadaj obrażenia [sword]5", I've decided to leave these as is, because it would require a pretty huge change to everything and the meaning seems clear to me.

For the other ones that were due to word choices, I decided to just go with your suggestions!

![image](https://user-images.githubusercontent.com/2874150/87915743-10a1fa00-caba-11ea-9eb2-34babdba2a5a.png)

Thanks!
