### ISSUE TITLE
[More Fluff] Stony Armor crash in Inventor PU

### ISSUE THREAD

**Issue by Splurmphy** [TerryCavanagh/diceydungeons.com#1663]
***Not quite sure where Mod crashes should be reported... will delete if this isn't the right place :P

Was doing a Parallel Universe Inventor run with More Fluff, clicked on a chest, and the game crashed (Steam, Mac). Error text file seems to indicate the chest had Stony Armor.

Crash report: [_error.txt](https://github.com/TerryCavanagh/diceydungeons.com/files/4216526/_error.txt)

**Comment by ncrecc** [comment]
Jacke might've made a typo somewhere. Here's his github issues page: https://github.com/JuniorUdale/MoreFluff/issues

(For future reference, you should probably only post bugs here if you're certain they're not just  because a modder messed up)

**Comment by JuniorUdale** [comment]
Ideally this github should only be used for base game crashes, or crashes that would occur in the base game even if a mod wasn't installed. This error seems to be because of a typo (which I believe I fixed in the latest patch - try updating!). In any event, it's because of a modded item, so my issues page would be better suited for this.

**Comment by Splurmphy** [comment]
Whoops—my b, wasn't super sure where to report this.
If someone could delete this Issue, that would be great :P

**Comment by ncrecc** [comment]
You are able to close your own issues, that's close enough.
