### ISSUE TITLE
Flame Spell- does regular damage instead of fire damage

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#1732]

**Comment by ncrecc** [comment]
As mentioned on dicecord, this also applies to Snowball and Fireball, so I think elemental attacks losing their elemental property when downgraded was an intentional theme that never quite caught on.

**Comment by TerryCavanagh** [comment]
Ah - this was actually intentional, though maybe a bad decision. Earlier in development I thought elemental damage would end up playing a larger role, so it made sense that the downgraded versions would lose their elemental "edge".

At this point in development, fixing this would mean changing half a dozen pieces of equipment to have new downgrades, as well as changing all the related localisations, so I'm kind of reluctant to do it. But I'll have a look at the specific equipment involved and see if it's worth it.
