### ISSUE TITLE
Steal gadget softlocks the game if you use it while equipment is animating in.

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1736]
https://streamable.com/zc7h8o

**Comment by TerryCavanagh** [comment]
(Thanks for creating this, @JuniorUdale!)

It looks like this old bug from previous versions is back in v1.8, probably due to the changes we made to equipment animation for the gamepad controls. 

Our previous fix was kind of a stopgap, which seems to not be working anymore. For v1.9 I'm going to dig into this line by line and fix it properly.

**Comment by TerryCavanagh** [comment]
Ok, fixed in v1.8.2!
