### ISSUE TITLE
There is no innate text for "strongice", defaults to "ERROR: INNATE TEXT NOT DEFINED"

### ISSUE THREAD

**Issue by TheMysticSword** [TerryCavanagh/diceydungeons.com#1747]

**Comment by TerryCavanagh** [comment]
Fixed! Also added a string for strongshock while I was at it.

Thinking about this a bit, I've changed how innate strings are displayed. Now, if it isn't hardcoded into the game, it'll display as the exact string instead of "ERROR: INNATE TEXT NOT DEFINED". So, for example, you can use "is very disappointed with you" as your innate string, and it'll display as "INNATE: Baby Squid is very disappointed with you" rather than displaying an error.
