### ISSUE TITLE
Add variant of <d6> that does not get affected by free dice modifier

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/diceydungeons.com#1777]
Currently there's no way to use a proper dice slot in the description of an item without having it be affected by a free dice modifier. I think this would be a useful feature for modders to have, and I'm requesting it because of my particular case. Here's the current upgrade for one of my items:
![currentupgraded](https://user-images.githubusercontent.com/66463691/85072712-c655f200-b176-11ea-9c1b-8f76d694b13e.png)

Compared to the one that I initially designed and was unable to implement due to the description:
![idealupgrade](https://user-images.githubusercontent.com/66463691/85072756-d4a40e00-b176-11ea-93dc-75000fc32b5a.png)

(The dice slot here is a symbol and does not function)

**Comment by TerryCavanagh** [comment]
![fakeclub](https://user-images.githubusercontent.com/2874150/87904873-d8dd8700-caa6-11ea-8a46-315f670385d2.gif)

Done! You can now use the variable `<d6_withoutbonus>` in equipment strings to exclude free dice slots. (unfortunately implementing `<slot1>`, `<slot2>` etc would require a pretty major rewrite, so that's probably not going to happen, even though I agree that would be nice to have)
