### ISSUE TITLE
AI should peek into scripts provided by runscript

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#1858]
If an enemy equipment has a runscript pointing to blah.hx, and blah.hx is ``bonus(9999); trace("bonus points!");``, the AI won't even consider using it if the equipment doesn't do something else that would award points. If modders really don't want a script to be viewable by AI they can just lock it behind if(!simulation)

**Comment by TerryCavanagh** [comment]
This one is just not happening, I think - implementation issues aside, it could break existing stuff if AI suddenly started opening and parsing external scripts. Plus, doing so would be extremely slow in most cases, since AI scripts run a lot more than execute scripts! I would strongly discourage modders from *letting* the AI run external scripts. There's a very straightforward alternate way to tell the AI what to do in this situation, which is to use bonus scores, which is what I do and what I'd recommend.

**Comment by ncrecc** [comment]
that makes sense and that's generally the philosophy used nowadays - even back when people were using `new elements.Skill("mycoolskill").execute(self,target)` as an early version of runscript i think ai couldn't peek in there either, or there would've been skills being instantiated *constantly* every time minmax looked around.
(runscript is 2 years old now? jesus)
