### ISSUE TITLE
Enemies attack noticably faster when Val rule is active (1.9)

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#1870]
https://streamable.com/0vazu4

**Comment by TerryCavanagh** [comment]
This bug ended up being a really subtle, nightmarish thing to track down. Fixed it, though.

Basically, the script that restores your equipment at the end of your turn messes with the animation variables for the start of the enemy turn, because that bit of the animation system is still from the old 7drl version of the game.

There's a big chunk of code here which I would love to just strip out and rewrite, but I'm worried that fixing it properly now could cause all sorts of other mysterious issues that I probably don't have time to find out for Switch - it's too risky to mess with. 

Since this seems to be the only vanilla bug that this animation system actually causes, I'm just gonna leave it in place for now, and maybe mess with it in future.
