### ISSUE TITLE
Modding: Deck.getcards("discard") doesn't work

### ISSUE THREAD

**Issue by plasmaster09** [TerryCavanagh/diceydungeons.com#2167]
There's meant to be four arguments for Deck.getcards:
all- all the cards in the deck
inplay- all the cards that have entered the hand this turn
draw- all the cards that have yet to enter the hand
discard- all the cards in the discard pile
However, Deck.getcards("discard") is bugged and always returns an empty set.

**Comment by TerryCavanagh** [comment]
Oh, this sort of does work - it’s just misleading because Dicey Dungeons doesn’t actually have a real discard pile! The way it works is, the in-play pile is discarded at the end of your turn, shuffled, then immediately played back into the bottom of your deck. So if you fetch a list of this deck, it’s always empty.

There probably shouldn’t be a function to try to get this pile I guess, but now with the modding api at 1.0, I can’t make these kind of changes! So closing this.
