### ISSUE TITLE
Monstercards can be overwritten by regular cards with the same name (an item sharing its name with an enemy)

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2201]
![image](https://user-images.githubusercontent.com/11216597/100062687-01cbab00-2dfe-11eb-8521-343b326a3ea4.png)
As a kludge you can name the item e.g. Slime[] (where [] is a blank symbol) but that's not immediately obvious, and this bug can remain unknown to modders unless they happen to play backstage a lot

**Comment by TerryCavanagh** [comment]
I think this falls under the category of a "won't fix", because I can't imagine any fixes for this that wouldn't just make things worse. 

I could, for example, make it illegal to name items after fighters, but throwing an error here could potentially break existing mods. I could also try to guess the player's intent with a "smart" context sensitive fix, but that would likely just create new edge case issues if a modder tries to do something different than I expect (what if e.g. a modder somehow wants a passive card to appear in this view?). 

As you say, it's pretty easy to work around this from a modding perspective anyway, and at a certain point, it's up to modders to try to work around how the game works, not for the game to try to work around how mods work.
