### ISSUE TITLE
When you have blind in YCYL, dice on panel should become unblinded once you've "used up" all the blind

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#2255]

**Comment by TerryCavanagh** [comment]
I don't think this is correct: if the remaining dice on the panel were to be unblinded, it would give you additional information about the dice that you've already requested that you wouldn't otherwise have. Especially since in most cases you're only blinding a single dice, it would essentially tell you exactly what the value of the blind dice is.

The current implementation is a little cruel maybe, but it avoids this situation.
