### ISSUE TITLE
(Modding) Add a function to display enemy innates

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2287]
You can change innates fine (it's just an array), but if an enemy has no innates and you give them one, the little banner at the top doesn't show up.

**Comment by TerryCavanagh** [comment]
Done! In v1.11 you can use the command e.g. `target.addinnate("weakice");` to add an innate, and the game will animate the innate bar if it needs to.

![weakice](https://user-images.githubusercontent.com/2874150/106241040-438d2d80-6255-11eb-99d1-efe6016b7bf9.gif)

As an aside, it's possible to do this in v1.10! You just need to set `target.innateypos = 2;`, it turns out.
