### ISSUE TITLE
Consider adding some visual feedback to Rusty Sword to indicate when your health is "critical"

### ISSUE THREAD

**Issue by JuniorUdale** [TerryCavanagh/diceydungeons.com#2294]
Not everyone plays with the sound on, and not everyone knows that "critical" means "under 6, or under 25%". Consider adding a script to change its colour if your health drops below the threshold? Or just retooling it to say "double if your health is below 25%"

**Comment by onetruepurple** [comment]
How about this:

Default = brown card (because rust) with default description

If player.health is critical this turn = flash, become red, change description to say "Do <double> damage!"

**Comment by TerryCavanagh** [comment]
I like this suggestion: I've been meaning to buff Rusty Sword anyway, so I've gone ahead and done this too. 

Rusty Sword now changes colour when it's powered up (from red to yellow - it looked the best), can take any dice, and the threshold is now 50% instead of 25%/6 HP. Makes it a much more interesting item!
