### ISSUE TITLE
Consider simplifying the *Equipment card descriptions

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#2444]
Similar to https://github.com/TerryCavanagh/diceydungeonsbeta/issues/562 - the tooltip already explains what each *Equipment does, so is there really a need to describe it in the card that spawns it?

Removing the description would:

1. Simplify the cards. Instantly reduces the mental overhead!
2. Add a degree of mystery to each *Equipment card, and subsequent surprise when the player sees that it does something cooler than adding extra cards to their deck.
3. Free up space to add the once per battle tag, resolving #2442.

![image](https://user-images.githubusercontent.com/2095534/127740801-8c00f772-0098-468b-be76-ad30a293d6db.png)

**Comment by Matz-42** [comment]
I really dont think this is ideal at all. Especially since they're all shop equipments or things that require trading. This make all of them equipments that make are impossible to properly evaluate and that you need to commit to.

In an episode that already has a lot of hidden rules about its equipment generation, it's not ideal at all.
