### ISSUE TITLE
In Inventor Reunion, consider allowing countdown equipments up to CD16

### ISSUE THREAD

**Issue by Matz-42** [TerryCavanagh/diceydungeons.com#2479]
Currently it's only including CD equipments under 12 (So only 11 max, I feel like this a mistake and CD12 were meant to be included), which in my opinion is a shame because there are quite a lot of interesting equipments above that. 16 is still fairly reasonable as a countdown and this could lead to fun situations by including equipments like:

- Poison Slingshot (CD12)
- Chocolate Cookie (CD12)
- Dodge (CD16)
- Last Stand (CD12)
- First Aid Kit (CD16)
- Second Win (CD16)/ Encore (CD12) (Could be *really* fun)
- Raw Ambition (CD12)
- Rotten Core (CD16)
- Fool's Fire/Frost (CD12)
- Beetle Headbutt (CD12)
- Wicker (Gem)Staff (CD12)
- Sinkhole (CD12)
- (And a few other less noteworthy ones)

**Comment by TerryCavanagh** [comment]
Thanks for this issue! In general I think it's a good idea to rule out large countdowns, but I've made a few hardcoded exceptions for some things on this list that should be ok.

>Poison Slingshot
Rotten Core
Beetle Headbutt
Wicker Staff
Wicker Gemstaff

(Chocolate Cookie is unfortunately banned because the downgrade gives you re-equip next, which is banned from the episode)
