### ISSUE TITLE
Consider nerfing Poison Crown?

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#2673]
This has come up as an obvious danger point from a lot of testers. Fond as I am of it, it's probably going to lead to some ruined runs eventually...

**Comment by onetruepurple** [comment]
I like him. Needs to be re-evaluated after all 5 characters are playable with the new layouts though.

**Comment by JuniorUdale** [comment]
It's a fun item to steal (since it's fun to use it properly!), but it's very strong and has a surprisingly high potential to just kill someone on turn 1 (or at least, inflict an unreasonable amount of poison - it's pretty much guaranteed that *someone* is going to suffer a 15+ poison turn!)

I've kind of come around to liking the concept of "has the potential to just end you", but right now it's a bit too likely to happen. Maybe bump the countdown up to 6 (so he still technically CAN roll well enough to OTK you, but is much less likely to) and give him a couple of Rats?

**Comment by TerryCavanagh** [comment]
Ok, I've done it! I think so long as you have a nice high usage limit (I've gone for 10 uses per turn), you get the same effect without the risk of a mathematically possible infinite turn.
