### ISSUE TITLE
Witch + guild of power not working

### ISSUE THREAD

**Issue by BarbzYHOOL** [TerryCavanagh/diceydungeons.com#282]
Guild of power shocks one of my spell but doesn't give me an extra die each turn... What a bargain

**Comment by YinYin-Falcon** [comment]
It gives you a permanent additional dice once (on joining), not per turn.

You can then use the worst dice (you got one more) to unlock the stunned equipment each turn when required.

**Comment by BarbzYHOOL** [comment]
damn I saw "3 dices" and since i'm always with 3 dices with witch, I supposed it didn't work (first time I see that guild)

**Comment by BarbzYHOOL** [comment]
In fact, it's written "get an extra dice every turn". I swear, I am reading it right now

**Comment by YinYin-Falcon** [comment]
I know - and plenty of players expected it to work that way, which is why it's still an issue.

That dice is still a single permanent addition (for every turn not per turn ¯\_(ツ)_/¯), else it would be far too powerful.

All it'll take is removing "every turn" from the description I guess (or the dice part at least - stun is still every/per turn).

You get an extra dice, period.

**Comment by TerryCavanagh** [comment]
Yeah, sorry for the confusing description! This has been changed in v0.9. Thanks!
