### ISSUE TITLE
Equipment? text could be changeable

### ISSUE THREAD

**Issue by not-mario** [TerryCavanagh/diceydungeons.com#2895]
Maybe leave the first line as the title, similar to powercards

**Comment by TerryCavanagh** [comment]
Investigated this one a bit.

The short version is: a really nice, mod friendly implementation of this is very difficult to do now, because it causes problems with the localisations. But I can implement a quick hack to give you the functionality you actually want, so I'll do that. It works like this:

`Rules.altequipmentname = "CustomThing";`

The default value of the variable is `Equipment?`.

The main limitation with this is that you can't have multiple different labels for alternate equipment in a single episode, but it's the best I can do right now!
