### ISSUE TITLE
Make it clearer that the Thief is "stealing" equipment every turn

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#297]
This is p. confusing before you realise what's happening

**Comment by onetruepurple** [comment]
This could be solved in several ways:

- An explicit "Steal" gadget: this would be the actual clearest, and also tone down some of the UI woes (can't steal items until there's room in the inventory); however that could make it unusable in some situations (cannot make room for a 2x2 spell) and increases the number of clicks required

- If a text console is ever implemented, make it print "Thief steals [item] from [enemy]"

- Make the stolen item come to the screen from the right instead the left, and at a small delay: would be the simplest, and require no clicks; but also not immediately obvious

- Turn Steal into a card, like Backstab, but give it a countdown 0 so it always fires immediately: would immediately signify that it's an ability being used; could also be confusing and after some time players would prefer to just immediately start the turn with the stolen item instead

**Comment by onetruepurple** [comment]
Returning to my comment from a year ago:

Points 2 and 3 are almost certainly not happening. However, 1 and 4 are now more feasible because of certain advancements in development, specifically removing size 4 items and introducing passive items.

My suggestion would be to move forward with option 4, by making Thief's Stolen Card a passive card that either borrows equipment immediately on every turn, or magically turns into a borrowed card with a whiteflash.

**Comment by ncrecc** [comment]
is this still an issue worthy of being open?

**Comment by TerryCavanagh** [comment]
No, probably not going to make any changes here at this point. Though it is something that I should have probably thought harder about before launch in 2019, oh well!
