### ISSUE TITLE
Streamline warrior tweak UI

### ISSUE THREAD

**Issue by joshtriplett** [TerryCavanagh/diceydungeons.com#342]
The warrior's tweak ability is effectively a combination of a Nudge+ and a Bump+, with the restriction of only using one or the other per turn. So rather than having a single slot with arrows on the sides, what about having two slots, and adjusting the die immediately when dropping it in?

That would also fix the "use as holding area to prevent rerolling" issue (if you consider that a bug), since it wouldn't act as a holding area anymore.

**Comment by YinYin-Falcon** [comment]
This slot was introduced precisely because selectively holding dice from a reroll in any card (each used to have a play button) was no longer possible.

Last rework terry discussed was introducing a skill card similar to the cauldron, which simply allows rerolling a limited amount of individual dice per turn. That way you get to decide on many more smaller risks instead of a single whole set and there is no messing around with holding and tweaking.

**Comment by TerryCavanagh** [comment]
Yep, that's right! I have a particular plan here, as mentioned by @YinYin-Falcon.

I completely agree that this isn't feeling right - this just narrowly missed out on a redesign for v0.9, but should be sorted by v0.10.

**Comment by TerryCavanagh** [comment]
Ok, I'm trying something dramatic and new for v0.10 here! Thanks!

![warriorreroll](https://user-images.githubusercontent.com/2874150/42291230-5bb85560-7fc2-11e8-84ea-ccf9fa2e60c2.gif)
