### ISSUE TITLE
Stop Ice and Fire from cancelling each other out

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#347]
While it of course "makes sense", in practice it just makes both status effects weaker. I think it would feel ok if they didn't cancel each other out.

I could even push it further, and have fire target higher dice too - but do it in stages - if you've got 3 dice, and 1 burn and 1 frozen status, then the ice would apply first, and then the NEXT highest dice could get burnt.

**Comment by joshtriplett** [comment]
The same problem applies to weaken and shock; if a piece of equipment gets both weakened and shocked, when un-shocked the result is the un-weakened version. They should both work on the same equipment, so that the enemy has to unshock it and then they have the weakened version.

Otherwise, for instance, if you're relying on weaken to keep you alive, shock will get you killed. For instance, if you weaken the Barbarian's "Fist" equipment, it goes from 4 damage reusable to 3 damage non-reusable. If you then have Magic Armor, you can generate just enough shield to avoid taking damage. But if you also shock the Fist, the barbarian can un-shock it and then use it normally without the weaken, and you die.

**Comment by TerryCavanagh** [comment]
Fixed. Made a new issue about the weaken/shock problem, thanks!

https://github.com/TerryCavanagh/diceydungeons.com/issues/367
