### ISSUE TITLE
Cards currently equipped sometimes shift into a position where you can't insert a 1x2 card

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#354]
If you have four 1 by 1 cards, and have them all arranged in a 2x2 block on the left side of your inventory, if you gain a 1 by 2 card, you won't have enough space to equip it until you check your inventory and find that the cards have automatically sorted themselves such that only a 2 by 1 card will fit.

This also happens if you have two 1 by 1 cards, and one 1 by 2 card. The cards will shift to form a T shape, so you can't insert another 1 by 2 until you rearrange them.

**Comment by TerryCavanagh** [comment]
This still happens, sort of, because I still have the issue of inventory rearranging itself weirdly during various screen transitions. However, this particular issue is basically a symptom of https://github.com/TerryCavanagh/diceydungeons.com/issues/1054, so closing this one as essentially a duplicate.
