### ISSUE TITLE
Dodge needs to be made more robust

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#489]
```
if your opponent has Dodge and you use a Cauldron, you don't even get the dice.
```

**Comment by onetruepurple** [comment]
Also applies to Marotte and (presumably) Boomerang

**Comment by joshtriplett** [comment]
This does make Dodge quite nice as the player, though, against certain types of opponents.

Would it make sense to have a rarer "Stifle" that's "stop next equipment from taking effect", perhaps give that to a final boss that would otherwise have Dodge, and then have Dodge be just "stop all damage from the next equipment"?

**Comment by YinYin-Falcon** [comment]
It also eats the counterfeit device (in .13).

**Comment by onetruepurple** [comment]
This issue was confusing, so I've attempted to split it into #998 and #999.

**Comment by TerryCavanagh** [comment]
Gonna aim to fix this one for launch too!

**Comment by TerryCavanagh** [comment]
Finally fixed this one!

I've decided to make the following change as the new expected behaviour: Dodge now dodges the damage and status effect part of an action, but not things like rerolling dice. So e.g. If Loud Bird dodges cauldron, you won't do any damage, but you'll still get your dice back.

I added a "Script: On Dodge" column to equipment.csv to support this!
