### ISSUE TITLE
Initial loading failure, with error about lime

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#534]
![unknown](https://user-images.githubusercontent.com/2874150/46431671-51454d80-c744-11e8-9fd6-9ebbbf029b79.png)

I *suspect* this is a unicode file path thing. One person with this issue reported that the game worked correctly when launched from the itch.io app.

**Comment by TerryCavanagh** [comment]
Ah, that assumption might be wrong - I just tried running the game from a folder with a unicode filepath, and it worked fine. Shrug!

**Comment by mrcdk** [comment]
This happens when the game can't load the lime library (lime.ndll) for one reason or another. AFAIK there's not a clear fix for this because anything can be an issue:
- An antivirus or some other program locking the file.
- The user mistakenly deleting the file
- The file not being downloaded correctly
- ...

I'm more inclined towards an overzealous antivirus locking the file than anything else.

**Comment by TerryCavanagh** [comment]
Ok! I have an update about this! 

I checked, and it seems like the download is intact and nothing is deleting the lime dll. However, this person in this case is running at 32 bit operating system.

**Comment by TerryCavanagh** [comment]
Fixed! (hopefully)
