### ISSUE TITLE
Stage 3D error: Context3D not available

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#555]
![context3d](https://user-images.githubusercontent.com/2874150/46466556-880e7880-c7c3-11e8-9853-b6487f9706fe.png)

![cmdprompt](https://user-images.githubusercontent.com/2874150/46466560-89d83c00-c7c3-11e8-99ae-928dbb11672b.png)

![image](https://user-images.githubusercontent.com/2874150/46466575-9197e080-c7c3-11e8-93cb-7d27445c26b5.png)

I've had two reports of this now - it appears to happen when the user doesn't have a 3D card driver installed.

This might not be fixable, but if that is the case, we should try to improve this error message, and give clear instructions on how to fix the problem on their end.

**Comment by mrcdk** [comment]
This can't be fixed by us. It happens when the opengl context isn't available:
- The graphics drivers aren't installed or aren't loaded correctly.
- Drivers crashed for some reason and opengl can't be initialized again.
- The user disabled the graphics drivers.

I've commited a change to the error message that is shown.

**Comment by TerryCavanagh** [comment]
Fixed!
