### ISSUE TITLE
Advancing from the end of the player's turn sometimes takes uncomfortably long

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#598]
Seems to be triggered by pressing "end turn" after you've used a card but before it fully goes off-screen. The cards all linger around for about five seconds, which gives the appearance that the game has softlocked, but then they wipe off-screen like normal and the enemy's turn (or level-up screen) begins.

**Comment by TerryCavanagh** [comment]
Ah! Interestingly, this was a work around for a serious softlock bug that started around version 0.11 - I haven't figured out how to solve it yet, but what I did is add a time out to various animations so that if something goes wrong, at least it doesn't lock up the game.

Still need to figure this out properly...

**Comment by ncrecc** [comment]
This is very vague and I don't think anything lingers for a full 5 seconds anymore.
