### ISSUE TITLE
Odd difference in kerning between Camouflage+ and Camouflage

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeons.com#609]
![](https://i.frogbox.es/l36)

**Comment by Wowfunhappy** [comment]
Looks like in DD's font, the "5" numeral has a slightly longer width than the "3" numeral. That is in turn pushing the word "dice" slightly further to the right, and changing how the letters get mapped on the pixel grid.

This is obviously Terry's call, but if it were me, I would say this is not a bug—just a consequence of how fonts work! :)

**Comment by TerryCavanagh** [comment]
The weird thing here, though, is that it appears that *only* the i character is moving - and I’m not sure why that is! (I do agree that this is pretty low priority though)

**Comment by Wowfunhappy** [comment]
It has to do with rounding when the letters are mapped to the pixel grid. I.e., the letters are likely being moved a *very* small amount, but it just so happens that "i" is right at the threshold between one pixel and the next. So, the "i" gets pushed to the next pixel, but because the overall amount changed very little, it doesn't affect the other letters.

I work at a design agency and see this kind of thing all the time.

**Comment by TerryCavanagh** [comment]
Oh, interesting! Yeah, that makes sense!
