### ISSUE TITLE
Bully will sometimes use a 3 on a rock when they could just use fists

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#642]
The AI doesn't have any way to recognise the value of holding on to the rock cards over using fists. Using a once per battle card needs to be slightly dis-incentivised in the scoring.

**Comment by iestynne** [comment]
Might be fun to take an ML approach and let the computer decide all of the score values for itself.

Use the adversarial approach: create two AIs with slightly different scoring values, then pit them against each other for 100 games. Take the winner and generate more AI variants from it for the next round, etc. Leave this running for a few hours/days and see what turns out to be the optimal strategy.

**Comment by TerryCavanagh** [comment]
That could be fun, for sure :) But for v0.16, I've kludged a fix for this, which is good enough!

**Comment by iestynne** [comment]
Sure, I know you indie devs are just overflowing with free time for these kinds of experiments ;)
