### ISSUE TITLE
New Wicker Man AI is irrational

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#678]
Sometimes it completely fails to heal, since most of the time it assigns dice to items oddly i.e. low rolls going into Staff, rather than Healing Crystals, leaving the high ones unused.

It also should never ever touch burning dice (as per the weakness to fire) unless desperately needed to fire the attack.

**Comment by pace212** [comment]
Also, I'm pretty sure I just saw Wicker Man end his turn with an unused 3 that could have gone into a Healing Crystal. Confirmed! He did it again! His roll was 3 3 3 1 3. He had 11hp. Wicker Man's AI priorities are messed up in general - he'll put low dice into Staff, leaving high dice unusable, instead of using the low dice on healing and still having plenty of pips for Staff. Another roll was 4 2 2 4 3, he also left the 3 unused with a Healing Crystal still on the table, with only 6hp.

**Comment by TerryCavanagh** [comment]
![image](https://user-images.githubusercontent.com/2874150/50717742-9d749680-1081-11e9-85e8-a43a313d6db9.png)

**Comment by TerryCavanagh** [comment]
(I think healing is just really badly scored by the AI. Might need to take another look at that.)

**Comment by TerryCavanagh** [comment]
Wicker Man has had a major redesign for v0.16, and no longer uses healing crystals!
