### ISSUE TITLE
Reconsider Witch level 3 rewards

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#713]
Meteor is interesting, but only of interest to very specific builds. Also, Upgrade is just so clearly a better choice than prepared that it's weird to offer it at all. Consider these changes:

 - Just offer the upgrade as the level 3 required reward.
 - Make the prepared spell slots available in shops for 4-5 gold (this will require some recoding)
 - Offer Meteor alongside another spell for the level 3 optional rewards - think of something that's an interesting alternative!

**Comment by Colgateinuntap** [comment]
I disagree on upgrade being clearly better reward than prepared. I always pick prepared over upgraded. By the time I have to choose between 2nd prepared slot and 2nd upgraded slot, I have duplicate from previous level up and lockpick from 2nd floor shop(at least I think it is guaranteed). This means all I need to go infinite is roll 6 with 1 or 2. With two lockpicks prepared, I can guarantee, that any roll with 6 goes infinite, but with 2 upgraded and only 1 lockpick prepared, there is chance to failure even if I roll 6. 1 upgraded slot is enough, because you just override whatever there was anyway, but 1 prepared slot makes it harder to get to the infinite.

**Comment by TerryCavanagh** [comment]
Interesting, thank you!

With this change, I'd still be making prepared slots available, only as items available in shops instead of level up rewards.

**Comment by TerryCavanagh** [comment]
Trying a pretty drastic change here for v0.16 that amounts to a major buff. Let's see how it goes!
