### ISSUE TITLE
Crystal Sword isn't reusable in Inevitability of Rust

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeons.com#725]
Or at least the upgraded version isn't.

**Comment by onetruepurple** [comment]
Same applies to Flamethrower in v0.16.3

**Comment by TerryCavanagh** [comment]
Randomly selected bug time!

So, this one is effectively solved - I changed the generator and level up rewards some time ago so that you never see once per battle equipment in this episode, which is the correct approach, I think. It's a little ambiguous exactly how once per battle equipment *should* work in this episode, and the episode is weird enough that the extra complication really isn't needed.

Closing!
