### ISSUE TITLE
Trader didn't take exchanged equipment

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#758]
![image](https://user-images.githubusercontent.com/2874150/50717710-3525b500-1081-11e9-8909-a9d446c4ed8c.png)

**Comment by ncrecc** [comment]
Probably because if the player's current equipment grid is completely packed and player trades a small card for a large card, the received card will be too large to fit in there and goes to inventory as is standard for cards that don't fit in the current equipment grid - but in the process it forgets to actually _trade_ the card, and you end up with both cards.

**Comment by ncrecc** [comment]
(This bug is still around!)

**Comment by ncrecc** [comment]
This is a duplicate of #569 but not sure which issue should close

**Comment by TerryCavanagh** [comment]
This one has been fixed for a while. Closing!
