### ISSUE TITLE
v0.15.1 Quest notes: Robot - Dice for a Price

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#780]
- Ditch Fuse. It takes the whole fun out of the quest.
 - All the level up rewards for this quest are broken. Extra CPU does nothing, and most equipment doesn't make sense.
 - What should you get at level up in place of extra CPU?

**Comment by TerryCavanagh** [comment]
YinYin on the discord made some good defences for fuse, which I'll post here for reference:

```
hmm - but the dice I wanted is still locked
that's quite the punishment already
```

```
I still really like it as a concept - like if there was only one that's 2 large you start out with - no extra fuses

or - make them break permanently (like why is it back after burning through once?)
a bit like scrap on the inventor!
```

```
it might work on the others [quests] too
soaking an error once
if they are one use only - you gotta think hard when to equip them - or save them for later
```

**Comment by DiceWithDeath** [comment]
I agree with wanting to keep Fuse! It is maybe a bit too easy as a mode, but fuse helps with needing more strategy - you don't _always_ have to use every number right away. Fuse is the only thing that really makes (I forget its name but the sword that is 'add 1 for each roll') worthwhile in this mode.

Making it take 2 spaces (upgradable to 1 space) and only having 1 available would help. I'd prefer if they didn't disappear right away (or if they did, make them much more available - e.g. can buy for 1 coin in every shop, since so far in my run most of the shop items have been useless).

**Comment by DiceWithDeath** [comment]
Also, I'm not sure if the name totally captures the mode? I thought maybe something like 'use it or lose it', though that sorta implies a different kind of mode. 'You choose, you lose'?

But mainly for the description - it didn't really explain to me what it was going to be like. Not sure if the mode was changed and this is why?
It currently says: 'Sure, you lose some equipment each time you do so.' and '- Equipment randomly disappears for the turn as you create dice.'
I feel like those should be: 'Sure, you risk losing some equipment each time you do so.' and '- Each time you create a dice, 50% chance to lose one random piece of equipment for that turn.'


Can the 'you've received +2 CPU!' be removed since it's useless in this mode? Not essential, but it feels a bit pointless to look at.

**Comment by TerryCavanagh** [comment]
Thanks for the title suggestion, @DiceWithDeath! I'm trying it out for v0.16!

I made a few changes here, but this one is still going to need work I think.

**Comment by TerryCavanagh** [comment]
For v0.17, I made a number of changes to equipment distribution that I think are all pretty fun. You find more "needs X" equipment, which is really good on this mode, as well as more countdown equipment, which has a kind of built in push your luck aspect to it.

The big remaining problem with this mode is level up rewards, which I still need to figure out!

**Comment by TerryCavanagh** [comment]
Some tweaks needed here, and some bugs to fix, but feeling very happy with this episode. The biggest thing to figure out is level up rewards. Closing.
