### ISSUE TITLE
Make blind less "fixable"

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeons.com#796]
Blind is more interesting if it's strict! Right now, it's kind of a nothing status effect, because it's usually so easy to work around it.

 - [x] If you use Duplicate, Lockpick, Spanner, Combat Roll, or other dice manipulation tools on a blind dice, the resulting dice should also be blind.
 - [x] Implement that robot range thing (https://github.com/TerryCavanagh/diceydungeons.com/issues/467)
 - [x] Using a blind dice on a multi slot equipment shouldn't reveal the value of the dice:

![image](https://user-images.githubusercontent.com/2874150/51076207-437d5d80-168d-11e9-989b-c6cb67c27aad.png)

**Comment by YinYin-Falcon** [comment]
#467 :)

I still think an action where the only use is rerolling a single dice (warrior skill) could remove blindness, since you are still using up a resource/option and have no other incentive for it otherwise. It's often interesting to agonise over just using blinded dice to save the combat roll for improving others or to spend the combat roll on revealing it. Very similar to, but not quite the same as silence.

**Comment by lcenine** [comment]
> Using a blind dice on a multi slot equipment shouldn't reveal the value of the dice:

That's the only one that really bothers me because it is taking advantage of something that could be fixed (put "?" instead of the dice value and that would be fixed.) The other 2 scenarios.. Duplicate/lockpick, etc all consume a card, so I think that' s fine. Robot I would say it was an innate ability.

**Comment by ncrecc** [comment]
Pretty sure item 1 can be checked off!

**Comment by TerryCavanagh** [comment]
Tagging this one with Random Bug Lottery, since fixing https://github.com/TerryCavanagh/diceydungeons.com/issues/200 will also require finally fixing this one!

**Comment by TerryCavanagh** [comment]
Fixed! Multislot equipment no longer reveals the value of blinded dice.

![image](https://user-images.githubusercontent.com/2874150/85247701-32499a80-b496-11ea-86f7-2fe3f5c88390.png)
